/* autogenerated by Processing revision 1292 on 2023-03-23 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class JumpingCircle extends PApplet {

int r = 25;
int velx = 3, vely = 5, posx = 300, posy = 240;

public void setup() {
   /* size commented out by preprocessor */;
}

public void draw() {
  background(255);
  fill(0);
  posx += velx;
  posy += vely;
  if(posx < r || posx > width-r) velx = -velx;
  if(posy < r || posy > height-r) vely = -vely;
  circle(posx, posy, 1.5f*r);
}


  public void settings() { size(640, 480); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "JumpingCircle" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
